/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AirdropsService } from "../airdrops.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AirdropsCreateInput } from "./AirdropsCreateInput";
import { Airdrops } from "./Airdrops";
import { AirdropsFindManyArgs } from "./AirdropsFindManyArgs";
import { AirdropsWhereUniqueInput } from "./AirdropsWhereUniqueInput";
import { AirdropsUpdateInput } from "./AirdropsUpdateInput";
import { CommentsFindManyArgs } from "../../comments/base/CommentsFindManyArgs";
import { Comments } from "../../comments/base/Comments";
import { CommentsWhereUniqueInput } from "../../comments/base/CommentsWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AirdropsControllerBase {
  constructor(
    protected readonly service: AirdropsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Airdrops })
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAirdrops(
    @common.Body() data: AirdropsCreateInput
  ): Promise<Airdrops> {
    return await this.service.createAirdrops({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        partakeLink: true,
        postedAt: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Airdrops] })
  @ApiNestedQuery(AirdropsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async airdropsItems(@common.Req() request: Request): Promise<Airdrops[]> {
    const args = plainToClass(AirdropsFindManyArgs, request.query);
    return this.service.airdropsItems({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        partakeLink: true,
        postedAt: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Airdrops })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async airdrops(
    @common.Param() params: AirdropsWhereUniqueInput
  ): Promise<Airdrops | null> {
    const result = await this.service.airdrops({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        partakeLink: true,
        postedAt: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Airdrops })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAirdrops(
    @common.Param() params: AirdropsWhereUniqueInput,
    @common.Body() data: AirdropsUpdateInput
  ): Promise<Airdrops | null> {
    try {
      return await this.service.updateAirdrops({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          image: true,
          partakeLink: true,
          postedAt: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Airdrops })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAirdrops(
    @common.Param() params: AirdropsWhereUniqueInput
  ): Promise<Airdrops | null> {
    try {
      return await this.service.deleteAirdrops({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          image: true,
          partakeLink: true,
          postedAt: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/commentsItems")
  @ApiNestedQuery(CommentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comments",
    action: "read",
    possession: "any",
  })
  async findCommentsItems(
    @common.Req() request: Request,
    @common.Param() params: AirdropsWhereUniqueInput
  ): Promise<Comments[]> {
    const query = plainToClass(CommentsFindManyArgs, request.query);
    const results = await this.service.findCommentsItems(params.id, {
      ...query,
      select: {
        airdrop: {
          select: {
            id: true,
          },
        },

        airdropRelation: true,
        content: true,
        createdAt: true,
        downvotes: true,
        id: true,
        relAirdrop: true,
        relUser: true,
        updatedAt: true,
        upvotes: true,

        user: {
          select: {
            id: true,
          },
        },

        userRelation: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/commentsItems")
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "update",
    possession: "any",
  })
  async connectCommentsItems(
    @common.Param() params: AirdropsWhereUniqueInput,
    @common.Body() body: CommentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commentsItems: {
        connect: body,
      },
    };
    await this.service.updateAirdrops({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/commentsItems")
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "update",
    possession: "any",
  })
  async updateCommentsItems(
    @common.Param() params: AirdropsWhereUniqueInput,
    @common.Body() body: CommentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commentsItems: {
        set: body,
      },
    };
    await this.service.updateAirdrops({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/commentsItems")
  @nestAccessControl.UseRoles({
    resource: "Airdrops",
    action: "update",
    possession: "any",
  })
  async disconnectCommentsItems(
    @common.Param() params: AirdropsWhereUniqueInput,
    @common.Body() body: CommentsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      commentsItems: {
        disconnect: body,
      },
    };
    await this.service.updateAirdrops({
      where: params,
      data,
      select: { id: true },
    });
  }
}
