/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NotificationsService } from "../notifications.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotificationsCreateInput } from "./NotificationsCreateInput";
import { Notifications } from "./Notifications";
import { NotificationsFindManyArgs } from "./NotificationsFindManyArgs";
import { NotificationsWhereUniqueInput } from "./NotificationsWhereUniqueInput";
import { NotificationsUpdateInput } from "./NotificationsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NotificationsControllerBase {
  constructor(
    protected readonly service: NotificationsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Notifications })
  @nestAccessControl.UseRoles({
    resource: "Notifications",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNotifications(
    @common.Body() data: NotificationsCreateInput
  ): Promise<Notifications> {
    return await this.service.createNotifications({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        message: true,
        notificationMessage: true,
        relUserNotification: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userNotification: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Notifications] })
  @ApiNestedQuery(NotificationsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Notifications",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notificationsItems(
    @common.Req() request: Request
  ): Promise<Notifications[]> {
    const args = plainToClass(NotificationsFindManyArgs, request.query);
    return this.service.notificationsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        message: true,
        notificationMessage: true,
        relUserNotification: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userNotification: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Notifications })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Notifications",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notifications(
    @common.Param() params: NotificationsWhereUniqueInput
  ): Promise<Notifications | null> {
    const result = await this.service.notifications({
      where: params,
      select: {
        createdAt: true,
        id: true,
        message: true,
        notificationMessage: true,
        relUserNotification: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userNotification: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Notifications })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Notifications",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNotifications(
    @common.Param() params: NotificationsWhereUniqueInput,
    @common.Body() data: NotificationsUpdateInput
  ): Promise<Notifications | null> {
    try {
      return await this.service.updateNotifications({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          message: true,
          notificationMessage: true,
          relUserNotification: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userNotification: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Notifications })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Notifications",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNotifications(
    @common.Param() params: NotificationsWhereUniqueInput
  ): Promise<Notifications | null> {
    try {
      return await this.service.deleteNotifications({
        where: params,
        select: {
          createdAt: true,
          id: true,
          message: true,
          notificationMessage: true,
          relUserNotification: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userNotification: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
